Vistas/app/__init__.py
from flask import Flask
import pymysql.cursors
from config import Config

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    connection = pymysql.connect(
        host=app.config['MYSQL_HOST'],
        user=app.config['MYSQL_USER'],
        password=app.config['MYSQL_PASSWORD'],
        database=app.config['MYSQL_DB'],
        cursorclass=pymysql.cursors.DictCursor
    )

    from app.controllers.user_controller import user_bp

    app.register_blueprint(user_bp)

    app.connection = connection

    return app


Vistas/app/controllers/user_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, current_app
from flask_bcrypt import Bcrypt
from flask import session

user_bp = Blueprint('user_bp', __name__)
bcrypt = Bcrypt()

@user_bp.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        connection = current_app.connection
        try:
            with connection.cursor() as cursor:
                cursor.execute("SELECT Contraseña FROM usuario WHERE email=%s", (email,))
                result = cursor.fetchone()
                if result and bcrypt.check_password_hash(result['Contraseña'], password):
                    session['user_email'] = email
                    return redirect(url_for('user_bp.inicio'))
                else:
                    return redirect(url_for('user_bp.login'))
        except Exception as e:
            return str(e)
    return render_template('login.html')

@user_bp.route('/inicio', methods=['GET', 'POST'])

def inicio():
    connection = current_app.connection
    try:
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT piloto.Nombre_Piloto, piloto.Num_Identificación, piloto.Fecha_Nacimiento, equipo.Nombre_Equipo, aviones.Nombre_Avion
                FROM piloto
                JOIN equipo ON piloto.ID_Equipo = equipo.ID
                JOIN aviones on piloto.ID_Aviones = aviones.ID
            """)
            team_pilot = cursor.fetchall()
    except Exception as e:
        return str(e)
    
    try:
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM equipo")
            team = cursor.fetchall()

            cursor.execute("SELECT * FROM aviones")
            planes = cursor.fetchall()

            cursor.execute("SELECT * FROM circuito")
            race = cursor.fetchall()
    except Exception as e:
        return str(e)
    
    return render_template('index.html', team_pilot=team_pilot, team=team, planes=planes, race=race)

@user_bp.route('/registro', methods=['GET', 'POST'])
def registro():
    connection = current_app.connection
    if request.method == 'POST':
        name = request.form['name']
        email = request.form['email']
        password = request.form['password']
        fecha_n = request.form['fecha']
        hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
        try:
            with connection.cursor() as cursor:
                cursor.execute("INSERT INTO usuario (Nombre, Email, Contraseña, Fecha_Nacimiento) VALUES (%s, %s, %s, %s)", (name, email, hashed_password, fecha_n))
                connection.commit()
            return redirect(url_for('user_bp.login'))
        except Exception as e:
            return str(e)
    return render_template('registro_usuarios.html')

@user_bp.route('/piloto', methods=['GET', 'POST'])
def piloto():
    connection = current_app.connection
    if request.method == 'POST':
        name = request.form['name']
        cedula = request.form['cedula']
        fecha = request.form['fecha']
        equipo = request.form['equipo']
        avion = request.form['avion']
        try:
            with connection.cursor() as cursor:
                cursor.execute("INSERT INTO piloto (Nombre_Piloto, Num_Identificación, Fecha_Nacimiento, ID_Equipo, ID_Aviones) VALUES (%s, %s, %s, %s, %s)", (name, cedula, fecha, equipo, avion))
                connection.commit()
            return redirect(url_for('user_bp.inicio'))
        except Exception as e:
            return str(e)
    try:
        with connection.cursor() as cursor:
            cursor.execute("SELECT ID, Nombre_Equipo FROM equipo")
            equipos = cursor.fetchall()
    except Exception as e:
        return str(e) 
    
    try:
        with connection.cursor() as cursor:
            cursor.execute("SELECT ID, Nombre_Avion FROM aviones")
            aviones = cursor.fetchall()
    except Exception as e:
        return str(e)
        
    return render_template('registro_piloto.html', equipos=equipos, aviones=aviones)

@user_bp.route('/equipo', methods=['GET', 'POST'])
def equipo():
    connection = current_app.connection
    if request.method == 'POST':
        name = request.form['name']
        personas = request.form['people']
        mecanicos = request.form['mecanic']
        try: 
            with connection.cursor() as cursor:
                cursor.execute("INSERT INTO equipo (Nombre_Equipo, Personas_Equipo, Mecanicos_Equipo) VALUES (%s, %s, %s)", (name, personas, mecanicos))
                connection.commit()
            return redirect(url_for('user_bp.inicio'))
        except Exception as e:
            return str(e)
    return render_template('registro_equipos.html')

@user_bp.route('/circuito', methods=['GET', 'POST'])
def circuito():
    connection = current_app.connection
    if request.method == 'POST':
        name = request.form['name']
        maxim = request.form['cantidad']
        km = request.form['kilometros']
        try:
            with connection.cursor() as cursor:
                cursor.execute("INSERT INTO circuito (Nombre_Circuito, Cantidad_Max_Participantes, Km_Circuito) VALUES (%s, %s, %s)", (name, maxim, km))
                connection.commit()
            return redirect(url_for('user_bp.inicio'))
        except Exception as e:
            return str(e)
    return render_template('registro_circuito.html')

@user_bp.route('/avion', methods=['GET', 'POST'])
def avion():
    connection = current_app.connection
    if request.method == 'POST':
        name = request.form['name']
        number = request.form['number']
        silla = request.form['place']
        km = request.form['recorrido']
        try:
            with connection.cursor() as cursor:
                cursor.execute("INSERT INTO aviones (Nombre_Avion, Numero_Avion, Cantidad_Asientos, Km_Recorridos) VALUES (%s, %s, %s, %s)", (name, number, silla, km))
                connection.commit()
            return redirect(url_for('user_bp.inicio'))
        except Exception as e:
            return str(e)
    return render_template('registro_aviones.html')




Vistas/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Inicio
            
        </title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <link href="../static/styles.css" rel="stylesheet" />
    </head>
    <body id="page-top">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
            <div class="container px-4">
                <a class="navbar-brand" href="#page-top">Winners</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="#about">Ganadores</a></li>
                        <li class="nav-item"><a class="nav-link" href="#services">Registrar</a></li>
                        <li class="nav-item"><a class="nav-link" href="#contact">Registros</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <header class="bg-primary bg-gradient text-white">
        </header>
        <section id="about">
            <div class="container px-4">
                <div class="row gx-4 justify-content-center">
                    <div class="col-lg-8">
                        <h2 class="text-center">Pilotos Ganadores</h2>
                        <table class="table mt-5 text-center">
                            <thead>
                              <tr>
                                <th scope="col">Nombre</th>
                                <th scope="col">Numero de avión</th>
                                <th scope="col">Nombre del equipo</th>
                                <th scope="col">Circuito Ganado</th>
                                <th scope="col">Tiempo del Ganador</th>
                              </tr>
                            </thead>
                            <tbody>
                              <tr>
                                <td>Andres</td>
                                <td>5433234</td>
                                <td>TopGun</td>
                                <td>CLean</td>
                                <td>08:16:04</td>
                              </tr>
                              <tr>
                                <td>Julian</td>
                                <td>4223542</td>
                                <td>Stelar</td>
                                <td>Alter</td>
                                <td>10:20:15</td>

                              </tr>
                              <tr>
                                <td>Andrea</td>
                                <td>1245234</td>
                                <td>Magics</td>
                                <td>Dead</td>
                                <td>02:15:02</td>
                              </tr>
                            </tbody>
                          </table>
                    </div>
                </div>
            </div>
        </section>
        <section class="bg-light" id="services">
            <div class="container px-4">
                <div class="row justify-content-center">
                    <div class="col-3 text-center">
                        <h3>Registar Piloto</h3>
                        <a href="{{ url_for('user_bp.piloto') }}" class="btn btn-primary mt-4">Registrar</a>
                    </div>
                    <div class="col-3 text-center">
                        <h3>Registrar Equipo</h3>
                        <a href="{{ url_for('user_bp.equipo') }}" class="btn btn-primary mt-4">Registrar</a>
                    </div>
                    <div class="col-3 text-center">
                        <h3>Registrar Circuito</h3>
                        <a href="{{ url_for('user_bp.circuito') }}" class="btn btn-primary mt-4">Registrar</a>
                    </div>
                    <div class="col-3 text-center">
                        <h3>Registar Aviones</h3>
                        <a href="{{ url_for('user_bp.avion') }}" class="btn btn-primary mt-4">Registrar</a>
                    </div>
                </div>
            </div>
        </section>
        <section id="contact">
            <div class="container px-4">
                <div class="row gx-4 justify-content-center text-center">
                    <div class="col-6">
                        <h4>Pilotos Registrados</h4>
                        <table class="table mt-5 text-center">
                            <thead>
                              <tr>
                                <th scope="col">Nombre</th>
                                <th scope="col">Identificación</th>
                                <th scope="col">Fecha Nacimiento</th>
                                <th scope="col">Equipo</th>
                                <th scope="col">Avion</th>
                              </tr>
                            </thead>
                            <tbody>
                              {% for contact in team_pilot %}
                                  <tr>
                                      <td> {{ contact.Nombre_Piloto }} </td>
                                      <td> {{ contact.Num_Identificación }} </td>
                                      <td> {{ contact.Fecha_Nacimiento }} </td>
                                      <td> {{ contact.Nombre_Equipo }} </td>
                                      <td> {{ contact.Nombre_Avion }} </td>
                                  </tr>
                              {% endfor %}
                            </tbody>
                          </table>
                    </div>
                    <div class="col-6">
                        <h4>Equipos Registrados</h4>
                        <table class="table mt-5 text-center">
                            <thead>
                              <tr>
                                <th scope="col">Nombre Equipo</th>
                                <th scope="col">Personas en el equipo</th>
                                <th scope="col">Numero de mecanicos</th>
                              </tr>
                            </thead>
                            <tbody>
                              {% for equipo in team %}
                                <tr>
                                  <td> {{equipo.Nombre_Equipo}} </td>
                                  <td> {{equipo.Personas_Equipo}} </td>
                                  <td> {{equipo.Mecanicos_Equipo}} </td>
                                </tr>
                              {% endfor %}
                            </tbody>
                          </table>
                    </div>
                </div>
            </div>
            <div class="container px-4 mt-5 text-center">
                <div class="row  justify-content-center">
                    <div class="col-6">
                        <h4>Circuitos registrados</h4>
                        <table class="table mt-5 text-center">
                            <thead>
                              <tr>
                                <th scope="col">Nombre del circuito</th>
                                <th scope="col">Participantes</th>
                                <th scope="col">Km del circuito</th>
                              </tr>
                            </thead>
                            <tbody>
                              {% for carrera in race %}
                                <tr>
                                  <td> {{carrera.Nombre_Circuito}} </td>
                                  <td> {{carrera.Cantidad_Max_Participantes}} </td>
                                  <td> {{carrera.Km_Circuito}} </td>
                                </tr>
                              {% endfor %}
                            </tbody>
                          </table>
                    </div>
                    <div class="col-6">
                        <h4>Aviones Registrados</h4>
                        <table class="table mt-5 text-center">
                            <thead>
                              <tr>
                                <th scope="col">Nombre del avion</th>
                                <th scope="col">Numero del avion</th>
                                <th scope="col">Cantidad de asientos</th>
                                <th scope="col">Kms recorridos</th>
                              </tr>
                            </thead>
                            <tbody>
                              {% for plane in planes %}
                                <tr>
                                  <td> {{plane.Nombre_Avion}} </td>
                                  <td> {{plane.Numero_Avion}} </td>
                                  <td> {{plane.Cantidad_Asientos}} </td>
                                  <td> {{plane.Km_Recorridos}} </td>
                                </tr>
                              {% endfor %}
                            </tbody>
                          </table>
                    </div>
                </div>
            </div>
        </section>
        <footer class="py-5 bg-dark">
            <div class="container px-4"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="../static/scripts.js"></script>
    </body>
</html>

Vistas/app/templates/registro_aviones.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Registro de Aviones</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <link href="../static/estilos.css" rel="stylesheet" />
    </head>
    <body class="sb-nav-fixed">    
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    <h1 class="text-center mt-3">Registro de Aviones</h1>
                    <section class="container">
                        <form class="row g-3 mt-5" method="POST" action="{{ url_for('user_bp.avion') }}">
                            <div class="col-md-6">
                                <label for="input1erNombre" class="form-label">Nombre del avion</label>
                                <input type="text" class="form-control" id="name" name="name" required> 
                            </div>
                            <div class="col-md-6">
                                <label for="input1erNombre" class="form-label">Numero del avión</label>
                                <input type="text" class="form-control" id="number" name="number" required> 
                            </div>
                            <div class="col-md-6">
                                <label for="inputCedula" class="form-label">Cantidad de asientos</label>
                                <input type="number" class="form-control" id="place" name="place" required>
                            </div>
                            <div class="col-md-6">
                                <label for="inputFechaContratoInicio" class="form-label">Kms recorridos</label>
                                <input type="number" class="form-control" name="recorrido" required>
                            </div>
                            <div class="col-12 d-flex justify-content-center mt-5">
                                <button type="submit" class="btn btn-primary px-3 me-3">Guardar</button>
                                <a href="{{ url_for('user_bp.inicio') }}" class="btn btn-danger" >Cancelar</a>
                            </div>
                        </form>
                    </section>
                </div>
            </main>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="assets/demo/chart-area-demo.js"></script>
        <script src="assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
        <script src="js/datatables-simple-demo.js"></script>
    </body>
</html>

Vistas/app/templates/registro_circuito.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Registro de Aviones</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <link href="../static/estilos.css" rel="stylesheet" />
    </head>
    <body class="sb-nav-fixed">    
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    <h1 class="text-center mt-3">Registro de Circuitos</h1>
                    <section class="container">
                        <form class="row g-3 mt-5" method="POST" action="{{ url_for('user_bp.circuito') }}">
                            <div class="col-md-6">
                                <label for="input1erNombre" class="form-label">Numero del Circuito</label>
                                <input type="text" class="form-control" id="name" name="name" required> 
                            </div>
                            <div class="col-md-6">
                                <label for="inputCedula" class="form-label">Cantidad Maxima de Participantes</label>
                                <input type="number" class="form-control" id="cantidad" name="cantidad" required>
                            </div>
                            <div class="col-md-6">
                                <label for="inputFechaContratoInicio" class="form-label">Kms del circuito</label>
                                <input type="number" class="form-control" name="kilometros" required>
                            </div>
                            <div class="col-12 d-flex justify-content-center mt-5">
                                <button type="submit" class="btn btn-primary px-3 me-3">Guardar</button>
                                <a href="{{ url_for('user_bp.inicio') }}" class="btn btn-danger" >Cancelar</a>
                            </div>
                        </form>
                    </section>
                </div>
            </main>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="assets/demo/chart-area-demo.js"></script>
        <script src="assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
        <script src="js/datatables-simple-demo.js"></script>
    </body>
</html>

Vistas/app/templates/registro_equipos.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Registro de Equipos</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <link href="../static/estilos.css" rel="stylesheet" />
    </head>
    <body class="sb-nav-fixed">    
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    <h1 class="text-center mt-3">Registro de Equipos</h1>
                    <section class="container">
                        <form class="row g-3 mt-5" method="POST" action="{{ url_for('user_bp.equipo') }}">
                            <div class="col-md-6">
                                <label for="input1erNombre" class="form-label">Nombre del Equipo</label>
                                <input type="text" class="form-control" id="name" name="name" required> 
                            </div>
                            <div class="col-md-6">
                                <label for="inputFechaContratoInicio" class="form-label">Personas en el equipo</label>
                                <input type="number" class="form-control" name="people" required>
                            </div>
                            <div class="col-md-6">
                                <label for="inputFechaContratoInicio" class="form-label">Mecanicos en el equipo</label>
                                <input type="number" class="form-control" name="mecanic" required>
                            </div>
                            <div class="col-12 d-flex justify-content-center mt-5">
                                <button type="submit" class="btn btn-primary px-3 me-3">Guardar</button>
                                <a href="{{ url_for('user_bp.inicio') }}" class="btn btn-danger" >Cancelar</a>
                            </div>
                        </form>
                    </section>
                </div>
            </main>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="assets/demo/chart-area-demo.js"></script>
        <script src="assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
        <script src="js/datatables-simple-demo.js"></script>
    </body>
</html>

Vistas/app/templates/registro_ganadores.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Registro de Aviones</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <link href="../static/estilos.css" rel="stylesheet" />
    </head>
    <body class="sb-nav-fixed">    
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    <h1 class="text-center mt-3">Registro de Circuitos</h1>
                    <section class="container">
                        <form class="row g-3 mt-5" method="POST" action="{{ url_for('user_bp.circuito') }}">
                            <div class="col-md-6">
                                <label for="input1erNombre" class="form-label">Nombre Piloto</label>
                                <input type="text" class="form-control" id="name" name="name" required> 
                            </div>
                            <div class="col-md-6">
                                <label for="inputCedula" class="form-label">Nombre del Avion</label>
                                <input type="text" class="form-control" id="avion" name="name_plane" required>
                            </div>
                            <div class="col-md-6">
                                <label for="inputFechaContratoInicio" class="form-label">Nombre del equipo</label>
                                <input type="text" class="form-control" name="equipo" required>
                            </div>
                            <div class="col-md-6">
                                <label for="inputFechaContratoInicio" class="form-label">Circuito Ganando</label>
                                <input type="number" class="form-control" name="name_race" required>
                            </div>
                            <div class="col-md-6">
                                <label for="inputFechaContratoInicio" class="form-label">Fecha de la victoria</label>
                                <input type="number" class="form-control" name="date_victory" required>
                            </div>
                            <div class="col-12 d-flex justify-content-center mt-5">
                                <button type="submit" class="btn btn-primary px-3 me-3">Guardar</button>
                                <a href="{{ url_for('user_bp.inicio') }}" class="btn btn-danger" >Cancelar</a>
                            </div>
                        </form>
                    </section>
                </div>
            </main>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="assets/demo/chart-area-demo.js"></script>
        <script src="assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
        <script src="js/datatables-simple-demo.js"></script>
    </body>
</html>